Semana 4
undefined-academy/semana-4 pull request #101
Opened 2023-05-15 21:00 UTC by EdwinOrtizCantillo

# Semana 4

## Ejercicio 1
Crear un nuevo proyecto npm init -y e instala lodash como dependencia: npm install lodash.
Luego agregue "type": "module" al package.json
Desarrollé una función que dada una fecha nos permita "humanizarla" con las siguientes reglas:
- Si la fecha es menos de un mes, mostrarla de manera humana, por ejemplo Hace 7 minutos , Hace 2 días , Hace 3 semanas.
- Si la fecha es más de un mes, mostrar mes y día, por ejemplo marzo 25.
- Si la fecha no es el mismo año, mostrar la fecha completa: enero 15 2021.

## Ejercicio 2
Actualicé el CV y Blog para utilizar variables y módulos con SASS.
- Desarrollé un set de una serie de archivos dónde main.scss cargara base.scss, reset.scss, desktop.scss, entre otros; mediante @use (así de esta manera evitamos utilizar el @import por buenas prácticas), base.scss tiene los estilos mobile first y desktop.scss tendrá la variación para escritorio, los colores se encuentran en el archivo variables.scss.
## Ejercicio 3
- Realice el fork del repositorio de la semana-4 https://github.com/undefined-academy/semana-4
y realice los ejercicio solicitados arriba.
- Realicé el pull request.

2023-05-16 15:57 UTC, brunom033 approved these changes

2023-05-16 16:05 UTC, EdwinOrtizCantillo commented
> ¿Hola como estás? Una simple observación, se podría modular parte del código del main.js del blog en otros archivos dentro de utils para un mejor ordenamiento pero la verdad que está muy bien todo. Saludos.

Gracias lo voy intentar saludos

2023-05-16 16:45 UTC, EzequielCaste commented
@EdwinOrtizCantillo
Sobre el Blog: 
- no es responsivo (es decir que no se adapta a pantallas pequeñas como por ejemplo un celular) No es algo que se pida en la consiga del ejercicio pero sí es algo que se recomienda hacer.
- encontré una inconsistencia con el idioma del blog (español) y el locale del `dayjs`:
![image](https://github.com/undefined-academy/semana-4/assets/51804994/4af94da8-8015-40bc-9eba-1c652f5039c6)
para solucionar esto te recomiendo importar idioma español:
```
import es from "dayjs/locale/es.js";
dayjs.locale(es);
```

Con respecto al CV:
- revisar la alineación de las skills en pantallas pequeñas 400px

2023-05-16 16:47 UTC, EzequielCaste requested changes
muy bien :+1: 
una sola corrección con la importación del locale para dayjs.

Recomendación: Intenta ver tus páginas en modo mobile y verifica que todo se vea correctamente en pantallas pequeñas, medianas, y desktop.

2023-05-16 16:47 UTC, EzequielCaste commented on student-blogs/Edwin_Ortiz-3619/scr/scripts/utils/humanize.js
> +import("dayjs/locale/es-us.js");
```suggestion
import es from "dayjs/locale/es.js";
dayjs.locale(es);
```

2023-05-19 01:40 UTC, EdwinOrtizCantillo commented on student-blogs/Edwin_Ortiz-3619/scr/scripts/utils/humanize.js
> +import("dayjs/locale/es-us.js");
Dale hermano ya aplique el responsive al blog e hice unos cambios

2023-05-19 19:53 UTC, EzequielCaste approved these changes

2023-05-20 11:33 UTC, merged