Ejercicios de la Semana 4
undefined-academy/semana-4 pull request #107
Opened 2023-05-21 19:03 UTC by FreivysDev

Hola a todos, cree un nuevo Pull Request ya que fue cerrado el anterior porque me falto una revisión. Estare atento a sus comentarios y sugerencias. Gracias

2023-05-21 19:24 UTC, jorge9372 requested changes

2023-05-21 19:24 UTC, jorge9372 commented on student-blogs/freivys-4974/scss/main.scss
Hola, este archivo seria bueno que lo nombraras como variables ya que es lo que se encuentra dentro de el.

2023-05-21 19:24 UTC, jorge9372 commented on student-blogs/freivys-4974/scss/styles.scss
Este archivo debería ser tu main.scss

2023-05-21 19:24 UTC, jorge9372 commented on student-cvs/freivys-4974/main.mjs
Aca puedes comentar los console.log al final porque son solo pruebas con las fechas

2023-05-21 19:24 UTC, jorge9372 commented on student-cvs/freivys-4974/scss/main.scss
aca lo mismo solo tienes variables, puedes renombrar el archivo para que corresponda mas

2023-05-21 20:34 UTC, jorge9372 approved these changes

2023-05-21 20:34 UTC, jorge9372 commented on student-cvs/freivys-4974/main.mjs
> +/*
La estructura para comentar es así: 
```
/*
Comentarios asasjlasjkasjkasl
*/ 
```


por eso no te lo toma

2023-05-21 22:08 UTC, FreivysDev commented on student-cvs/freivys-4974/main.mjs
> +/*
> La estructura para comentar es así:
> 
> ```
> /*
> Comentarios asasjlasjkasjkasl
> */ 
> ```
> 
> por eso no te lo toma

Arreglado el error 👍

2023-05-29 21:34 UTC, Andrssnsdc approved these changes
excelente

2023-05-30 01:43 UTC, FreivysDev commented
> excelente

Hola Andersson, gracias por el approved 👍

2023-05-30 02:17 UTC, Andrssnsdc commented
por nada te agradezco si puedes revisar el mío https://github.com/undefined-academy/semana-4/pull/28

2023-05-30 13:53 UTC, merged