semana-4
undefined-academy/semana-4 pull request #109
Opened 2023-05-24 18:23 UTC by dhdarken

**Ejercicio de la semana-4**

1. primero hice el fork de la semana-4
2.  luego copie y pegue las carpetas de student-blogs y student-cvs de la semana -3 en la carpeta forkeada de la semana-4
3.  realice los ejercicios tanto del prepocesador Sass como de la funcion humanizada con la biblioteca del dayjs.

2023-05-26 16:44 UTC, EzequielCaste requested changes
has subido la carpeta node_modules con tu Pull Request, por favor elimínala.

2023-05-29 01:10 UTC, MrRedu requested changes
Hola, dhdarken. Intenté revisar tu carpeta, pero cuando entro a los archivos se me traba la PC, jajaj. Supondré que es por el `node_modules`

Por lo que pude ver (solo alcance a abrir el blog), te puedo sugerir algunas correcciones:
- Eliminar el `node_modules` (lo eliminas en tu repositorio local, y luego pusheas el commit y, en teoría ya estaría. Después puedes hacer `npm install` para instalar la carpeta en tu PC si la ocupas de vueta)
- La consistencia nombrando cosas, tenemos una carpeta con el nombre por la mitad, tenemos por otra parte nombres de imágenes con espacios, luego otro con - (guiones). No existe un "orden"
- El `main.scss` debe ir en la carpeta de styles, no en la carpeta principal. También nos falta el archivo de estilos donde deben ir las variables

No pude revisar el CV, porque se me traba la PC cuando intento abrir tus archivos en el CodeSpace, así que primero elimina el `node_module` que es algo *crítico *y sin problema sigo con la revisión

2023-05-29 01:10 UTC, MrRedu requested changes
Hola, dhdarken. Intenté revisar tu carpeta, pero cuando entro a los archivos se me traba la PC, jajaj. Supondré que es por el `node_modules`

Por lo que pude ver (solo alcance a abrir el blog), te puedo sugerir algunas correcciones:
- Eliminar el `node_modules` (lo eliminas en tu repositorio local, y luego pusheas el commit y, en teoría ya estaría. Después puedes hacer `npm install` para instalar la carpeta en tu PC si la ocupas de vueta)
- La consistencia nombrando cosas, tenemos una carpeta con el nombre por la mitad, tenemos por otra parte nombres de imágenes con espacios, luego otro con - (guiones). No existe una regla general.
- El `main.scss` debe ir en la carpeta de styles, no en la carpeta principal. También nos falta el archivo de estilos donde deben ir las variables

No pude revisar el CV, porque se me traba la PC cuando intento abrir tus archivos en el CodeSpace, así que primero elimina el `node_module` que es algo *crítico *y sin problema sigo con la revisión

2023-05-29 01:10 UTC, MrRedu requested changes
Hola, dhdarken. Intenté revisar tu carpeta, pero cuando entro a los archivos se me traba la PC, jajaj.
Supondré que es por el `node_modules`

Por lo que pude ver (solo alcance a abrir el blog), te puedo sugerir algunas correcciones:
- Eliminar el `node_modules` (lo eliminas en tu repositorio local, y luego pusheas el commit y, en teoría ya estaría. Después puedes hacer `npm install` para instalar la carpeta en tu PC si la ocupas de vueta)
- La consistencia nombrando cosas, tenemos una carpeta con el nombre por la mitad, tenemos por otra parte nombres de imágenes con espacios, luego otro con - (guiones). No existe una regla general.
- El `main.scss` debe ir en la carpeta de styles, no en la carpeta principal. También nos falta el archivo de estilos donde deben ir las variables

No pude revisar el CV, así que primero eliminamos el `node_module` que es algo *crítico *, y sin problema sigo con la revisión

2023-05-29 01:44 UTC, MrRedu approved these changes
¡Hola! Ahora sí pude revisar tu PR super cómodo. Definitivamente era el `node_modules`.
Te dejo algunas correcciones y algunas *recomendaciones*, las segundas no son necesarias.

Blog;
- Las mismas correcciones anteriores, con respecto a los `nombres`, `consistencia `, `lugar del main.scss` y modulo para las `variables.scss`. Recomiendo que te cheques rápido el README.md del repositorio, el cual te aclarará aún más el panorama.
- El header del blog no está adaptado a mobile. Aunque el Grid sí, bien ahí.
- Donde sale tu avatar, en cada card, podrías ponerle la etiqueta `<footer>` para que sea "menos incorrecto" a nivel semántico
- Falto agregar el` "type":"module"`, en el `package.json`, esto nos sirve cuando utilizamos módulos de JavaScript.
- Las etiquetas `<article>` suelen "necesitar" un `<header>`, ahí podrías agregar tu H1. Esto es meramente semántico, no ocasionará cambios en tu estilo

CV:
- Noté cómo está compuesta tu tabla de comandos, y está hecha con puros div. Creo que una buena manera sería cambiarlo a una table de HTML. Pero, a esta altura (semana-4), realmente recomendaría ya quitar los comandos y agregar información personal.
- El `"type":"module"` acá también

_Realmente confío en que las harás, así que te daré approved, y antes de enviarlo a merge, corrige algunas cosas_  💪🏼

2023-06-11 00:21 UTC, LizethCs approved these changes
Bien👍veo que ya realizaste los cambios que te solicitaron realizar.

2023-06-11 02:18 UTC, merged