Semana-4 Undefined Academy
undefined-academy/semana-4 pull request #111
Opened 2023-06-01 15:53 UTC by QuirogaPau

2023-06-01 18:00 UTC, aitorias requested changes
¡Hola Paula! Estuve revisando tu PR de la semana 4 y te hice algunos comentarios y sugerencias para el proyecto para que lo puedas revisar.

Respecto el cv, se ve MUY LINDO y ordenadito y la gama de colores, me encanta! 😄

2023-06-02 14:35 UTC, Arzeus17 approved these changes

2023-06-05 21:25 UTC, QuirogaPau commented on student-blogs/PaulaQuiroga-8406/styles/base.scss
Hola Aitor, muchas gracias por las sugerencias. Ahora me pongo a revisar, por ahí vuelva con preguntas porque fue algo que me mareó un poco jaja

2023-06-05 22:10 UTC, dhdarken requested changes

2023-06-05 22:10 UTC, dhdarken commented on student-blogs/PaulaQuiroga-8406/index.html
> +    <link rel="stylesheet" href="styles/main.css">
segun el argumento dado por el profe el main debe ir fuera de styles.

2023-06-05 22:10 UTC, dhdarken commented on student-blogs/PaulaQuiroga-8406/package.json
> +  "name": "paulaquiroga-8406",
falta  "type"="module" en tu json

2023-06-05 22:10 UTC, dhdarken commented on student-blogs/PaulaQuiroga-8406/styles/base.scss
> +@use "variables.scss" as variables;
como consejo puedes poner * en vez de variables para acceder a todo

2023-06-13 14:15 UTC, QuirogaPau commented
Hola, gracias chicos por los comentarios. Ahí realice los cambios sugeridos !!

2023-06-13 15:30 UTC, aitorias commented on student-cvs/PaulaQuiroga-8406/index.html
> +    <link rel="stylesheet" href="styles/main.css">
Recuerda que el `main.css` lo tienes en la raíz del proyecto, no dentro de la carpeta `styles/`.

2023-06-13 15:30 UTC, aitorias commented on student-blogs/PaulaQuiroga-8406/styles/desktop.scss
Veo que estos estilos los tienes duplicados en el archivo `base.scss`. Yo como recomendación, te diría que en este archivo utilices solo estilos dentro del `@media min-width` y los estilos genéricos los pases todos al archivo `base.scss` para evitar duplicidades y ahorrar en pesos de archivos.

2023-06-13 15:31 UTC, aitorias approved these changes
Buenas de nuevo Paula! Te hice de nuevo la validación y los cambios se ven perfectamente 😋 . Te hice algunos comentarios con correcciones de algunas cosas que vi. Por lo demás lo veo genial! 😄

2023-06-29 02:07 UTC, merged