PR Semana 4
undefined-academy/semana-4 pull request #113
Opened 2023-06-11 00:04 UTC by LizethCs

PR con los ejercicios de la semana 4

2023-06-11 01:30 UTC, dhdarken requested changes

2023-06-11 01:30 UTC, dhdarken commented on student-cvs/Lizeth-9127/package.json
> +  "name": "lizeth-9127",
te falta "type":"module "a tu json.

2023-06-11 01:30 UTC, dhdarken commented on student-cvs/Lizeth-9127/styles/base.scss
> +    90deg,
en vez de copiar variables puedes utilizar un * y te va a funcionar es a modo de consejo meramente.

2023-06-11 01:30 UTC, dhdarken commented on student-cvs/Lizeth-9127/main.scss
> +@use "styles/desktop";
te falta el @use "variables.scss";

2023-06-11 01:30 UTC, dhdarken commented on student-cvs/Lizeth-9127/index.html
> +        <script type="module" src="main.mjs"></script>
olvida lo del "type" veo que lo implementas en linea

2023-06-11 01:30 UTC, dhdarken commented on student-blogs/Lizeth-9127/index.html
>          <div class="flex-wrapper">
puedes empezar a experimentar por semantica mejorando con arciculos en vez de divs recuerda que divs esta bien para maquetar y despues ya deben ser cambiados .

2023-06-11 16:21 UTC, LizethCs commented
Gracias por los comentarios.  Ya realicé los cambios. Respecto a lo de añadir `@use "variables.scss";` en main.scss, no es necesario cargar las variables en el main ya que las variables las estoy cargando en base.scss (y main.scss carga a base.scss)

2023-06-12 01:14 UTC, dhdarken approved these changes

2023-06-13 21:27 UTC, merged