ejercicios de la semana 4
undefined-academy/semana-4 pull request #16
Opened 2023-04-05 00:27 UTC by fjquants

**Ejercicio de 1. Uso de Lodash**
Creé un archivo llamado index.js 
Instalé Lodash como dependencia de desarrollo
Utilicé lodash para filtrar base de datos

**Ejercicio 2. Función humanizar**
Creé una archivo llamado Fechas.js
Instalé Dayjs como dependencia
Redacté función

**Ejercicio 3. Actualizar CV y blogs**
Mediante uso de variable SASS actualicé los ejercicios de CV y blogs.

**Ejercicio 4. PR**
Hice fork del repositorio de la semana 4 a mi perfil de github
Cloné localmente
Realicé los ejercicios de la semana
Hice PR de los ejercicios

2023-04-06 16:22 UTC, MauBedoya requested changes
hay algunas cosas que revisar y completar el ejercicio de la última clase que consiste en manipular el DOM y utilizar la función para humanizar fechas.

2023-04-06 16:22 UTC, MauBedoya commented on student-blogs/fjquant-2458/styles/variables.scss
recuerda que hay que usar [Name that Color](https://chir.ag/projects/name-that-color/#6195ED) para asignarles nombres a las variables

2023-04-06 16:22 UTC, MauBedoya commented on student-blogs/fjquant-2458/styles/main.scss
> +    background-color: antiquewhite;
lo ideal sería que este estilo del body vaya en base o desktop y que en main solo queden los **@use**

2023-04-06 16:22 UTC, MauBedoya commented on student-blogs/fjquant-2458/Fechas.js
La idea del ejercicio es extraer fechas de tu HTML, humanizarlas y luego incrustar los resultados de nuevo en tu HTML, esto para el blog y para el CV.
Puedes darte una idea de cómo hacerlo revisando los PR de otros compañeros o el mío. 👀

2023-04-08 22:09 UTC, 4ngelo12 approved these changes
Te quedo bien.

2023-04-09 00:27 UTC, fjquants commented on student-blogs/fjquant-2458/styles/variables.scss
Revisé nuevamente los videos y tu ejercicio y finalmente pude asignar estas variables

2023-04-09 00:27 UTC, fjquants commented on student-blogs/fjquant-2458/Fechas.js
Ya lo pude incluir en el ejercicio del blog

2023-04-25 02:43 UTC, merged