Semana_04-SASS
undefined-academy/semana-4 pull request #23
Opened 2023-04-08 21:10 UTC by 4ngelo12

1.  Dentro de la terminal se escribe `npm init -y` para generar un archivo llamado `package.json`, luego de ello se instala las **sass** y **vite** como dependencias de desarrollo de la siguiente manera: 
- `npm install -D sass`
- `npm install -D sass`
2.  Ingresamos al  archivo `package.json` e ingresamos lo siguiente dentro del `"scripts"` `"dev": "vite",`
    `"sass": "sass styles/main.scss assets/css/main.css",` para poder ejecutar las dependencias instaladas.
3. Luego se crea una carpeta llamada **styles** donde guardaremos nuestros archivos con la extensión **.scss**. En mi caso use los siguientes archivos `base.scss`, `main.scss`, `desktop.scss`, `variables.scss` y `normalize.scss`.

2023-04-09 17:12 UTC, pablo-alex requested changes
Hola @4ngelo12 los estilos y el trabajo con los modulos y variables SASS me parece excelente. Solo no veo el ejercicio con las fechas y la libreria DayJS, no te olvides eso.

2023-04-09 17:12 UTC, pablo-alex commented on student-blogs/4ngel0-7040/styles/main.scss
Tal vez este arhivo podrias moverlo un nivel mas arriba, siguiendo la estructura recomendada

2023-04-09 17:12 UTC, pablo-alex commented on student-blogs/4ngel0-7040/index.html
> +                        <p>Hace 1 horas</p>
Una vez que tengas tu funcion humanizarFecha() podrias convertir una fecha en un formato estandar y convertirla a una humanizada donde "Hace 1 horas" seria el resultado

2023-04-09 19:56 UTC, pablo-alex approved these changes

2023-04-09 20:01 UTC, pablo-alex commented on student-blogs/4ngel0-7040/index.html
> +                        <p>Hace 1 horas</p>
@4ngelo12 Agradeceria si puedes darme tu review o sugerencias a mi [PR semana 4](https://github.com/undefined-academy/semana-4/pull/25)

2023-04-17 08:49 UTC, aitorias commented on student-blogs/4ngel0-7040/assets/js/main.js
> +function humanizarFecha(fecha) {
Muy genial el uso del _switch_ para resolver el ejercicio! 👍

2023-04-17 08:53 UTC, aitorias commented on student-blogs/4ngel0-7040/index.html
> +<html lang="en">
Nada que decir! Está genial! Sólo que recuerda cambiar el idioma en la etiqueta `html` a español (ya que este caso tienes el contenido así), pero nada, era solo una observación. Está lindo!

2023-04-17 08:54 UTC, aitorias commented on student-cvs/4ngel0-7040/about.html
Precioso el diseño! 👍

2023-05-04 02:11 UTC, closed without merging