Semana-4
undefined-academy/semana-4 pull request #27
Opened 2023-04-10 02:27 UTC by facu1391

### Ejercicio 1
* Se creo el archivo index.js en la carpeta student-cvs/student-blogs facundo91-1495  y se realizo el ejercicio solicitado.
### Ejercicio 2
* Se creo la funcion en el archivo main.mjs para humanizar las fechas en esta tambien se agrego al archivo index.html para cuando se verifique la hoja de vida se visualice los dias o la fecha que a pasado utilizando la funcion en el .mjs.
### Ejercicio 3
* Se realizo los archivos scss generando el @use para importar las variables y el archivo base y deskd desde main.scss.
### Ejercicio 4
* Se realizo el fork y se subieron los cambios realizados

2023-04-10 05:33 UTC, Cristhian-Medina requested changes
Agregaste Sass al proyecto, pero no lo has utilizado ninguna de sus utilidades en ninguna parte de las hojas de estilo.

2023-04-10 05:33 UTC, Cristhian-Medina commented on student-blogs/.gitignore
Te recomiendo que elimines este archivo, es innecesario, 
ya esta bien definido en la raíz del repositorio.

2023-04-10 05:33 UTC, Cristhian-Medina commented on student-blogs/facundo91-1495/blog/main.mjs
> +//console.log(dayjs().format("YYY-MM-DD"))
Te recomiendo que elimines todas las lineas comentadas, es una buena practica.

2023-04-10 05:33 UTC, Cristhian-Medina commented on student-cvs/.gitignore
Te recomiendo que elimines este archivo, es innecesario, 
ya esta bien definido en la raíz del repositorio.

2023-04-10 05:33 UTC, Cristhian-Medina commented on student-blogs/facundo91-1495/blog/styles/variables.scss
Veo que definiste variables de Sass, pero no vi que las utilizaras en ninguna de las hojas de estilo.
Si no las vas a utilizar, es mejor que elimines este archivo.

2023-04-10 05:33 UTC, Cristhian-Medina commented on student-cvs/facundo91-1495/cvs/styles/variables.scss
Veo que definiste variables de Sass, pero no vi que las utilizaras en ninguna de las hojas de estilo.
Si no las vas a utilizar, es mejor que elimines este archivo.

2023-04-11 00:00 UTC, facu1391 commented on student-blogs/.gitignore
Tienes toda la razón, no había dado cuenta! ya hare la corrección

2023-04-11 00:01 UTC, facu1391 commented on student-blogs/facundo91-1495/blog/main.mjs
> +//console.log(dayjs().format("YYY-MM-DD"))
Muchas gracias por la corrección, ya será modificado.

2023-04-11 00:02 UTC, facu1391 commented on student-cvs/facundo91-1495/cvs/styles/variables.scss
Ya hare las modificaciones, muchas gracias por la corrección

2023-04-12 02:14 UTC, Cristhian-Medina approved these changes
Todo quedo muy bien,
Me quedo faltando que utilizaras un poco mas las funcionalidades de Sass como la anidación de las clases de estilos.

2023-04-22 12:10 UTC, DevOld112 requested changes
Hola Facundo, como estas? Pudiste agregar la funcionalidad de humanizar fecha en tu html? No logro visualizarla

2023-04-22 19:38 UTC, facu1391 commented
> Hola Facundo, como estas? Pudiste agregar la funcionalidad de humanizar fecha en tu html? No logro visualizarla

Hola Wilmer, todo bien y vos como estas?  si la verdad que no me había dado cuenta! en breve estaré modificando la corrección. 
Muchas gracias

2023-04-23 15:54 UTC, DevOld112 commented
> > Hola Facundo, como estas? Pudiste agregar la funcionalidad de humanizar fecha en tu html? No logro visualizarla
> 
> Hola Wilmer, todo bien y vos como estas? si la verdad que no me había dado cuenta! en breve estaré modificando la corrección. Muchas gracias

Excelente, ahora si tienes mi approve :)

2023-04-23 15:55 UTC, DevOld112 approved these changes

2023-04-27 13:17 UTC, cadifilippo commented on .gitignore
> +node_modules
Ya está al comienzo el archivo

2023-04-27 13:18 UTC, cadifilippo requested changes
Mira los comentarios

2023-04-27 13:18 UTC, cadifilippo commented on .gitignore
> +package-lock.json
no debería ser necesaria esta línea

2023-04-28 09:28 UTC, cadifilippo approved these changes
LGTM

2023-04-28 09:28 UTC, merged