Ejercicios semana 4
undefined-academy/semana-4 pull request #34
Opened 2023-04-11 04:50 UTC by Alexisdc5

Se actualizó el código (CV y Blog) para poder utilizar variables y módulos SASS.
Los estilos de la versión de escritorio fueron reubicados en el archivo desktop.scss.
Se crea una la función para humanizar las fechas

2023-04-12 21:22 UTC, rdjgl24 requested changes
Te falta agregar la funcionalidad para mostrar las fechas en el html con la funcion de humanizar las fechas

2023-04-13 03:17 UTC, Alexisdc5 commented
> Te falta agregar la funcionalidad para mostrar las fechas en el html con la funcion de humanizar las fechas
Muchas gracias por la corrección, ya realice los cambios

2023-04-29 20:10 UTC, Vene15 approved these changes

2023-05-01 01:02 UTC, Alexisdc5 commented
> tambien debe de alguna forma mostrar una fecha humanizada en el html del cvs

ahí  agregue la fecha humanizada en el cvs , gracias por la corrección

2023-05-03 13:48 UTC, Alexisdc5 commented
> tambien debe de alguna forma mostrar una fecha humanizada en el html del cvs

2023-05-24 15:57 UTC, Arzeus17 commented
Me parece que esta correcto!

2023-05-24 16:00 UTC, Arzeus17 approved these changes

2023-06-05 13:17 UTC, merged