Estilos con sass, fecha humanizada
undefined-academy/semana-4 pull request #35
Opened 2023-04-11 12:52 UTC by Vene15

-Se actualizó el código (CV y Blog) para poder utilizar variables y módulos SASS.
-Se creó una la función para humanizar las fechas.

2023-04-11 13:37 UTC, JoseCamilo84 requested changes

2023-04-11 13:37 UTC, JoseCamilo84 commented on student-blogs/Vene15-3355/main.mjs
> +import dayjs from "dayjs";
Hola, se ve bien tu trabajo... lo único que te podría decir es que no veo que la función humanizada la estes usando en el blog

2023-04-11 13:38 UTC, JoseCamilo84 commented
Perdón escribí mal, si acaso tienes un tiempo me revisarías el mío, gracias

2023-04-11 22:33 UTC, JoseCamilo84 approved these changes

2023-04-13 01:58 UTC, Vene15 commented on student-blogs/Vene15-3355/main.mjs
> +import dayjs from "dayjs";
Hola!! muchas gracias por tu aporte...
No encuentro tu pull request para revisarlo.

2023-04-13 03:31 UTC, Alexisdc5 approved these changes
con la corrección de fecha ya todo se ve bien

2023-04-14 13:04 UTC, Vene15 commented on student-blogs/Vene15-3355/main.mjs
> +import dayjs from "dayjs";
Ya tiene merged tu commit!! no pude aprobarlo, pero se ve bien!!!

2023-04-14 21:04 UTC, JoseCamilo84 approved these changes

2023-04-15 19:31 UTC, merged