Week 4
undefined-academy/semana-4 pull request #41
Opened 2023-04-14 03:40 UTC by Josofico

# Finally we can put what we learn in week 4 in our project.

2023-04-23 02:41 UTC, Lealdos requested changes
I see that you have implemented CSS variables using ':root'. I'm not sure if it's a better option than using '$', but if that works for you, it's okay.

2023-04-23 02:41 UTC, Lealdos commented on student-blogs/kick-off-2479/package.json
> +    "sass": "^1.61.0",
Please add SASS to the dependencies section of your package.json file, as without it, you won't be able to style your application in the way it's currently implemented

2023-04-23 02:41 UTC, Lealdos commented on student-cvs/kick-off-2479/src/styles/base.scss
> +    display: block;
This element has already in block property, so this line is not necessary

2023-04-24 02:21 UTC, Lealdos approved these changes
everything done

2023-05-01 17:18 UTC, dlozanoc82 approved these changes
Good job. You can check my PR https://github.com/undefined-academy/semana-4/pull/84

2023-05-01 18:17 UTC, cadifilippo commented
Quita los cambios del gitignore, si lo necesitas puedes ignorar el propio gitignore

2023-05-01 23:44 UTC, Lealdos approved these changes

2023-05-12 18:21 UTC, cadifilippo commented on .gitignore
> +# Created by https://www.toptal.com/developers/gitignore/api/macos,node,nextjs,react,intellij,linux,windows
No debes agregar el gitignore en el PR

2023-05-12 18:21 UTC, cadifilippo requested changes
quitar .gitignore

2023-05-14 15:03 UTC, Josofico reviewed
Just deleting gitignore

2023-05-18 02:41 UTC, Josofico reviewed
Restarting

2023-05-18 03:44 UTC, Josofico reviewed
Done

2023-05-20 00:58 UTC, Josofico reviewed
Deleting files.

2023-06-04 20:29 UTC, Josofico reviewed
.

2023-06-16 03:36 UTC, merged