Ejercicios semana 4
undefined-academy/semana-4 pull request #56
Opened 2023-04-18 21:35 UTC by DanaiKongpan

2023-04-20 13:54 UTC, DevOld112 requested changes
Hola amigo, que tal? Porfa en el .gitignore agrega a `vite-proyect` y `node__modules` si recuerdas en la clase de esa semana el profe Guillermo hizo enfasis (si no me equivoco) que no queria ver la carpeta Node_modules en ningun PR.

2023-04-21 00:39 UTC, lucianogarriga requested changes
He realizado unos comentarios para que apliques en tu proyecto, para que puedas cumplir con los requisitos exigidos en esta PR 4. Avísame cuando lo realices así veo tus avances  y apruebo tu PR!

2023-04-21 00:39 UTC, lucianogarriga commented on student-blogs/magma.geek-5933/Styles/base.scss
> +@media screen and (min-width:980px) {}
Has dejado todo el codigo de la media query por fuera de las llaves {}. Te recomiendo revisar ese detalle

2023-04-21 00:39 UTC, lucianogarriga commented on student-blogs/magma.geek-5933/.gitignore
No es recomendable que subas un archivo vacío, y más si se trata del .gitignore como este caso. Te recomiendo que aquí coloques la carpeta de node_modules, ya que no se debe subir a ningun repositorio

2023-04-21 00:39 UTC, lucianogarriga commented on student-blogs/magma.geek-5933/Styles/desktop.scss
> +body {background:papaya
En base deberías tener el código base de scss, y en desktop el código relativo a las media queries (me parece que en este caso estan invertidos)

2023-04-21 00:39 UTC, lucianogarriga commented on student-blogs/magma.geek-5933/Styles/main.scss
> +
En este archivo no has importado las variables, y el archivo de las variables veo que está vacío (allí deberías guardar variables con los colores, por ejemplo)

2023-04-24 15:28 UTC, DanaiKongpan commented on student-blogs/magma.geek-5933/Styles/main.scss
> +
gracias

2023-04-24 15:34 UTC, DanaiKongpan commented on student-blogs/magma.geek-5933/Styles/desktop.scss
> +body {background:papaya
gracias

2023-04-24 15:36 UTC, DanaiKongpan commented on student-blogs/magma.geek-5933/Styles/base.scss
> +@media screen and (min-width:980px) {}
gracias

2023-05-10 02:11 UTC, closed without merging