Commit ejercicio semana 4
undefined-academy/semana-4 pull request #57
Opened 2023-04-18 23:28 UTC by Hcofanelli

2023-04-20 13:48 UTC, DevOld112 requested changes
Pudiste agregar la funcion de mostrar fecha en tu HTML? No logro visualizarlo en tu codigo.

2023-04-20 14:02 UTC, Hcofanelli commented
> Pudiste agregar la funcion de mostrar fecha en tu HTML? No logro visualizarlo en tu codigo.

hice la funcion en student-blogs/hcofanelli-9792/main.mjs, y esta linkeado en el html, solo que no agregue ninguna fecha que lo visualice, si es necesario lo actualizo y vuelvo a hacer el commit

2023-04-20 14:05 UTC, DevOld112 commented
> > Pudiste agregar la funcion de mostrar fecha en tu HTML? No logro visualizarlo en tu codigo.
> 
> hice la funcion en student-blogs/hcofanelli-9792/main.mjs, y esta linkeado en el html, solo que no agregue ninguna fecha que lo visualice, si es necesario lo actualizo y vuelvo a hacer el commit

Si puedes agregarlo, excelente, me parece que es parte del ejercicio de la semana 4 amigo. Apenas lo hagas te doy el approved

2023-04-21 02:08 UTC, DevOld112 approved these changes
Ahora si, excelente todo!

2023-06-08 02:40 UTC, closed without merging