añadiendo hora humanizada
undefined-academy/semana-4 pull request #6
Opened 2023-04-01 03:49 UTC by Alexis033

2023-04-03 03:28 UTC, jaardila-3 approved these changes
Veo correcta la estructura del ejercicio, las dependencias y todo en general, como recomendación utilizar el await para esperar que se resuelva la promesa del idioma en el js.
Si tiene tiempo le pido el favor revise el mío de la semana 4, PR # 12, Dev Ardila

2023-04-03 04:14 UTC, Alexis033 commented
> Veo correcta la estructura del ejercicio, las dependencias y todo en general, como recomendación utilizar el await para esperar que se resuelva la promesa del idioma en el js. Si tiene tiempo le pido el favor revise el mío de la semana 4, PR # 12, Dev Ardila

Gracias por la revisión, no sabía que el idioma de esa librería devolvía una promesa, voy a echarle un ojo.

2023-04-10 00:03 UTC, MauBedoya requested changes
El trabajo de las fechas esta bueno 👍. La estructura es un tanto diferente a la que se pide o recomienda en la práctica 4 pero al final también funciona. Creo que lo que habría que revisar es el contenido de **desktop** y **base** del CV para separar mejor los estilos.

2023-04-10 23:53 UTC, MauBedoya commented on student-cvs/Maikcol-2796/styles/desktop.scss
> +@media screen and (min-width:501px) {
ahh okok, entonces era por eso, bueno en caso de que sigamos manejando esta estructura en los siguientes PR sería bueno que le des una revisada poco a poco entonces, como para que no queden medio mezclados los archivos.

2023-04-10 23:54 UTC, MauBedoya approved these changes

2023-04-12 00:44 UTC, merged