Week 4 - CVS with sass styles finished
undefined-academy/semana-4 pull request #63
Opened 2023-04-21 22:27 UTC by DanRev

For this part, I just added my cv with sass styles applied. To complete this task, I followed the steps below. 
First, I copied my last project to the new path.
After that I start a new project with `npm init -y` and then install as developer dependencies sass and vite.
After that, I pass css styles to sass styles and test it.

When I see that everything works fine, I consider the task finished

2023-04-22 12:16 UTC, DevOld112 requested changes
Hola Dan, como estas?

Recuerda ver la estructura del proyecto como se plantea en las clases y en el github de Undefined, te falta la carpeta de `student-blog`

Tambien no olvides agregar la funcion de `humanizeDate (date)`en tus html.

2023-04-25 02:09 UTC, DanRev reviewed
Hola Wilmer.
Muchas gracias por tomarte el tiempo de revisar mi PR.
Ya quedo actualizado.
Gracias

2023-04-25 02:31 UTC, DevOld112 commented
Excelente Dan, tienes mi approve :)

2023-04-25 02:31 UTC, DevOld112 approved these changes

2023-04-27 13:16 UTC, merged