Ejercicio
undefined-academy/semana-4 pull request #67
Opened 2023-04-24 23:44 UTC by juanssanchezv

Para hace los ejercicios de esta semana primero se usó la librería de dayjs para manejar las fechas.
Luego se reajustó el código del blog para usar Sass
Luego se reajustó el código de la CV para usar Sass
Finalmente se organizó el código de acuerdo al formato del PR

2023-04-25 00:14 UTC, andrealvarez2d requested changes
Todo bien, pero faltaria implementar la funcion de humanizar fechas en los html

2023-05-06 20:07 UTC, andrealvarez2d approved these changes

2023-05-09 22:35 UTC, mpchaneton approved these changes
Hola!
cumpliste con los puntos del ejrcicio 4:
-responsive
-SASS
- f humanize
Muy lindo tu blog =)

2023-05-10 14:41 UTC, dfm555 requested changes
Elimina todos los archivos que terminan en .jpg:Zone.Identifier

2023-05-11 01:00 UTC, merged