feat: ✨ Week 4 Exercises
undefined-academy/semana-4 pull request #7
Opened 2023-04-01 14:17 UTC by AndryOre

# Week 4: CSS to SASS
- [x] 🎨 Add SASS to CV and Blog projects.
- [x] 📱 Use SASS modules for have mobile first styles and desktop styles.
- [x] 🔧 Use SASS variables.

# Week 4: Dates in JS
- [x] 📆 Create function to humanize dates using Day.JS.
- [x] 🖋️ Humanize Blog post dates.

2023-04-03 03:36 UTC, jaardila-3 requested changes
Cordial saludo compañero, le falta organizar los archivos en una estructura más entendible, revisa la propuesta hecha en el mismo repositorio, además no veo en el main.mjs del CV la función de humanizar fechas. Feliz día.

2023-04-03 03:39 UTC, jaardila-3 commented
Revisa el mío si te sirve para guiarte y además me ayudas con la revisión, es el PR 12 Dev Ardila, Gracias
Se me olvidaba preguntarle si ya hay un archivo .gitignore global porque tienes un archivo de esos en tus carpetas

2023-04-04 18:55 UTC, jaardila-3 approved these changes
Mejoro la estructura y me parece que cumple a cabalidad con el ejercicio

2023-04-15 04:00 UTC, AndryOre commented
Esperando el review

2023-05-17 02:15 UTC, closed without merging