Ejercicios Completos. Semana-4 🐼
undefined-academy/semana-4 pull request #71
Opened 2023-04-25 23:52 UTC by DivPanda

2023-04-26 05:08 UTC, Codemonster808 approved these changes

2023-04-26 05:08 UTC, Codemonster808 approved these changes

2023-04-26 10:24 UTC, Lmendev requested changes
Hola! Buen trabajo 👍 

Me parece que en los PRs deberían estar las modificaciones en las carpetas de los usuarios de discord `/student-blogs` y `/student-cvs`.

Estos archivos están en `/lodash` 🤔 Deberían moverse de ruta

2023-04-27 00:42 UTC, DivPanda commented on lodash/ejercicio-lodash-clase-1.js
> +import _ from "lodash"
Hola bro muchas gracias por tomarte el tiempo de hacerme una revisión! Me pondré con eso n.n Cualquier cosa si quieres que también te haga un review estoy a la orden por acá y en discord 🙌🏻

2023-04-28 10:17 UTC, Lmendev commented on lodash/ejercicio-lodash-clase-1.js
> +import _ from "lodash"
Estoy atento! 👌

2023-04-29 02:09 UTC, Lmendev approved these changes
Buenísimo! 💎

2023-05-09 22:13 UTC, DivPanda commented
Nooo stale no

2023-05-10 02:02 UTC, dfm555 commented
> Nooo stale no

jajajajaj

2023-05-10 02:03 UTC, merged