Week activities-4
undefined-academy/semana-4 pull request #74
Opened 2023-04-26 05:57 UTC by brayortepla12

[EJERCICIO]
Hacer fork del repositorio de la semana-4 https://github.com/undefined-academy/semana-4
Usar la función humanize realizada en el ejercicio de la clase 2 para mostrar las fechas de forma humana en el HTML.
Subir los cambios realizados en el ejercicio de la semana 3 y crear el pull request.

2023-04-26 12:54 UTC, lucianogarriga requested changes
En líneas generales se nota que has realizado un gran trabajo. Asimismo, te he dejado unas recomendaciones para que puedas revisarlas. Por otro lado, no he visto en qué partes de tus archivos html has implementado las funciones de humanizeDate. Quedo atento así te apruebo tu PR!

2023-04-26 12:54 UTC, lucianogarriga commented on student-cvs/Bryan_Ortega_Plata-1009/index.html
> +            alt="">
Recomendación: no dejar las img sin su respectivo alt.

2023-04-26 12:54 UTC, lucianogarriga commented on student-cvs/Bryan_Ortega_Plata-1009/index.html
> +              <h2>Porteafolio web</h2>
Cuidado con errores ortográficos

2023-04-26 12:54 UTC, lucianogarriga commented on student-blogs/Bryan_Ortega_Plata-1009/index.html
> +          <main>
No recomendaría realizar tantas etiquetas < main > dentro de un mismo archivo html. En su caso, podrias reemplazarlas por < article > o < section >

2023-04-26 13:01 UTC, diirf requested changes
Hola! Me ha gustado mucho tu cv y en general implementas muy bien el sass. Te dejé solo un pequeño cambio y añadir las fechas en el blog para que puedas aplicar el script.

2023-04-26 14:05 UTC, brayortepla12 commented on student-blogs/Bryan_Ortega_Plata-1009/index.html
> +  <link rel="stylesheet" href="/style/main.css" />
Muchas gracias por la observación, tarea resuelta.

2023-04-26 14:06 UTC, brayortepla12 commented on student-blogs/Bryan_Ortega_Plata-1009/index.html
> +          <footer>
Muchas gracias por la observación, tarea resuelta.

2023-04-26 14:06 UTC, brayortepla12 commented on student-blogs/Bryan_Ortega_Plata-1009/main.mjs
> +import dayjs from "dayjs"
Muchas gracias por la observación, tarea resuelta.

2023-04-26 14:26 UTC, brayortepla12 commented on student-cvs/Bryan_Ortega_Plata-1009/index.html
> +            alt="">
Muchas gracias por la observación, tarea resuelta.

2023-04-26 14:47 UTC, brayortepla12 commented on student-cvs/Bryan_Ortega_Plata-1009/index.html
> +            alt="">
Muchas gracias por la observación, tarea resuelta.

2023-04-26 17:38 UTC, lucianogarriga approved these changes
He visto que has corregido e implementado las recomendaciones que te hemos realizado. Genial buen trabajo!

2023-04-26 21:50 UTC, diirf approved these changes
Veo que realizaste todos los cambios, por alguna razón a mi no me carga el fichero de JS y no puedo ver las fechas. En la consola aparece como un error pero la verdad no logré saber por qué.

2023-04-26 21:53 UTC, brayortepla12 commented
Gracias, revisare lo del archivo js

2023-04-27 13:21 UTC, cadifilippo commented on .gitignore
Este archivo no debería ir

2023-04-27 13:21 UTC, cadifilippo requested changes
Quita el gitignore

2023-04-28 18:43 UTC, brayortepla12 commented on .gitignore
listo archivo eliminado

2023-04-29 22:45 UTC, cadifilippo approved these changes

2023-04-29 22:46 UTC, merged