PR - Semana 4
undefined-academy/semana-4 pull request #78
Opened 2023-04-28 01:08 UTC by LizethCs

PR con ~~las tareas~~ los ejercicios de la semana 4

2023-05-02 01:45 UTC, darioernesto-roca approved these changes
Hola Lizeth, muy buena implementación, me gusta el orden que aplicas en tu código. Veo que utilizaste la etiqueta span y el innerHTML para incluir las nuevas fechas humanizadas. Yo recurrí a una etiqueta time y use textContent, creo que las dos son válidas. Te invito a pasarte por mi PR para que compares y me ayudes con tu revisión. Tienes mi aprobado.

2023-05-24 04:40 UTC, FreivysDev requested changes
Hola Lizeth, me parecio muy bien el trabajo realizado. Te deje algunas sugerencias para que mejores el codigo, son solo unos pequeños detalles. 👍

2023-05-24 04:40 UTC, FreivysDev commented on student-blogs/Lizeth-9127/index.html
Hola Lizeth, excelente trabajo el que realizaste. Tengo unas sugerencias para que mejores tu codigo. Una opción seria agregar dentro de tu `<header>` una etiqueta `<h1>Lizeth</h1>` como logo de tu marca personal o la otra opción seria agregar dentro de la etiqueta `<div class="flex-wrapper">` un `<h1>Blogs</h1>` indicando el nombre de la pagina; de esta manera,  solo exista una unica etiqueta `<h1>` en la pagina y luego reemplazas por una etiqueta `<h2>` los titulos de los articulos

2023-05-24 04:40 UTC, FreivysDev commented on student-cvs/Lizeth-9127/index.html
> +        </div>
Muy buen trabajo, aca debes eliminar la linea **67**, ya que tienes un cierre de la etiqueta `</div>` sobrante

2023-05-24 04:40 UTC, FreivysDev commented on student-blogs/Lizeth-9127/main.mjs
Muy bien 👍

2023-06-10 02:30 UTC, closed without merging