Semana 4 - SASS
undefined-academy/semana-4 pull request #8
Opened 2023-04-02 20:22 UTC by MariaSolArroyo

# 🤓 SEMANA 4 
---------------

- [ 💻 ] Fork de la Semana 4 de **Undefined Academy** 
- [ 👤  ] Uso de la funcion Humanize para mostrar fechas de forma humana 
- [✔️ ] Cambio en los ejercicios de la **Semana 3** (Blog y CV) utilizando **SASS**

2023-04-04 01:16 UTC, truquinio approved these changes
Me gustó mucho el uso de la función humanize(date)

2023-04-19 04:45 UTC, INGCapaDev requested changes
Muy bonito diseño, solo que existe un problema con las variables de sass estas utilizando @use y no las reconoce cuando quiero ver el diseño con vite, realize el cambio a @import y funciono perfectamente te indicare exactamente en que lineas esta el fallo. 💡Cuando actualizes los cambios con gusto te doy el check por cierto muy buen trabajo👍⭐

2023-04-19 04:45 UTC, INGCapaDev commented on student-cvs/MariaSolArroyo-9830/src/styles/base.scss
> +@use "variables.scss";
cambia este  @use por @import

2023-04-19 04:45 UTC, INGCapaDev commented on student-cvs/MariaSolArroyo-9830/src/styles/desktop.scss
> +@use "variables.scss"
El mismo caso cambiar el @use

2023-04-19 04:45 UTC, INGCapaDev commented on student-cvs/MariaSolArroyo-9830/src/styles/main.scss
> +@use "variables.scss";
y por ultimo cambiar el @use de las variables por @import tambien

2023-04-19 23:08 UTC, MariaSolArroyo commented on student-cvs/MariaSolArroyo-9830/src/styles/main.scss
> +@use "variables.scss";
muchas gracias por tu comentario, ya deje corregido ese detalle! Desde ya gracias 😃

2023-04-20 02:12 UTC, INGCapaDev requested changes
Disculpa el @import era para las variables funcionaran en sass pero el css de desktop y el base si estaba bien con el @use

2023-04-20 02:51 UTC, MariaSolArroyo commented on student-cvs/MariaSolArroyo-9830/src/styles/main.scss
> +@use "variables.scss";
listo ahi corregi

2023-04-20 03:10 UTC, INGCapaDev commented
Buen trabajo excelente ✌️

2023-04-20 04:00 UTC, INGCapaDev approved these changes

2023-04-20 09:25 UTC, merged